Adds deployment cookbook with a set of examples/instructions
DAGWorks-Inc/burr pull request #394
Opened 2024-10-15 00:04 UTC by elijahbenizzy

It also has a few issues that function as placeholders. We'll want to centralize this more as we get more tooling in Burr itself.

## Changes

## How I tested this

## Notes

## Checklist

- [ ] PR has an informative and human-readable title (this will be pulled into the release notes)
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code passed the pre-commit check & code is left cleaner/nicer than when first encountered.
- [ ] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future TODOs are captured in comments
- [ ] Project documentation has been updated if adding/changing functionality.

2024-10-15 00:20 UTC, skrawcz requested changes

2024-10-15 00:20 UTC, skrawcz commented on docs/examples/deployment/aws.md
why are these deleted? I don't see anything new here.

2024-10-15 00:44 UTC, elijahbenizzy commented on docs/examples/deployment/aws.md
They were duplicates

2024-10-15 00:57 UTC, skrawcz commented on docs/examples/deployment/aws.md
There is some duplication under examples, but I'm not following what this PR is doing -- it's removing stuff from docs without adding to it?

2024-10-15 18:53 UTC, elijahbenizzy commented on docs/examples/deployment/aws.md
Those docs were examples. This links to them instead of duplicateing.

2024-10-16 05:24 UTC, skrawcz reviewed
Fixed up wording in places.

2024-10-16 05:24 UTC, skrawcz commented on docs/examples/deployment/index.rst
> +To deploy Burr in production, you need to do three things:
```suggestion
To deploy a Burr application in production, you need to do three things:
```

2024-10-16 05:24 UTC, skrawcz commented on docs/examples/deployment/index.rst
> +1. Place your application in a web server
```suggestion
1. Place your Burr application in some place you can trigger it. E.g. a web-service, a script, a library, etc.
```

2024-10-16 05:24 UTC, skrawcz commented on docs/examples/deployment/index.rst
> +2. Provisioning infrastructure
```suggestion
2. Provision infrastructure to run (1)
```

2024-10-16 05:24 UTC, skrawcz commented on docs/examples/deployment/infrastructure.rst
> +Burr is not opinionated about the method of deployment/cloud one uses. Any method that can run a python server will work
```suggestion
Burr is not opinionated about the method of deployment/cloud one uses. Any method that can run python code, or web-service will work
```

2024-10-16 05:24 UTC, skrawcz commented on docs/examples/deployment/web-server.rst
> +We largely use `fastAPI <https://fastapi.tiangolo.com/>`_ as our web server, but Burr can work with any python-friendly server framework
```suggestion
We like `fastAPI <https://fastapi.tiangolo.com/>`_, but Burr can work with any python-friendly server framework
```

2024-10-16 05:24 UTC, skrawcz commented on docs/examples/deployment/web-server.rst
> +- `Use typed state with Pydantic + FastAPI <https://github.com/DAGWorks-Inc/burr/tree/main/examples/typed-state>`_
```suggestion
- `Use typed state with Pydantic + FastAPI <https://github.com/DAGWorks-Inc/burr/tree/main/examples/typed-state>`_
- `Burr + FastAPI + docker <https://github.com/mdrideout/burr-fastapi-docker-compose>`_ by `Matthew Rideout <https://github.com/mdrideout>`_. This contains a sample web server API + UI + tracking server all bundled in one!
- `Docker compose + nginx proxy <https://github.com/DAGWorks-Inc/burr/tree/main/examples/email-assistant#running-the-ui-with-email-server-backend-in-a-docker-container>`_ by `Aditha Kaushik <https://github.com/97k>`_ for the email assistant example, demonstrates running the docker image with the tracking server.
```

2024-10-16 15:55 UTC, merged